spring:
  application:
    name: mock-producer
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8088

app:
  kafka:
    client-events-topic: client-events
    deal-events-topic: deal-events
    risk-events-topic: risk-events
    transaction-events-topic: transaction-events

springdoc:
  swagger-ui:
    path: /swagger-ui.html
